# -*- coding: utf-8 -*-
"""Creating_Reading_and _Writing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9V7FpYRFmS8en1JTetF9QTTb30VAF-R
"""

import pandas as pd

pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'],
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

pd.Series([1, 2, 3, 4, 5])

pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

wine_reviews = pd.read_csv("/content/winemag-data-130k-v2.csv")

wine_reviews.shape

wine_reviews.head()

wine_reviews = pd.read_csv("/content/winemag-data-130k-v2.csv", index_col=0)
wine_reviews.head()

