# -*- coding: utf-8 -*-
"""Data_Types_and_Missing_Values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGXADzm2WatPZUZMt5oHU1ta3Uc3jABu
"""

import pandas as pd
reviews = pd.read_csv("/content/winemag-data-130k-v2.csv", index_col=0)
pd.set_option('display.max_rows', 5)

reviews.price.dtype

reviews.dtypes

reviews.points.astype('float64')

reviews.index.dtype

"""**Missing data**"""

reviews[pd.isnull(reviews.country)]

reviews.region_2.fillna("Unknown")

reviews.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

