# -*- coding: utf-8 -*-
"""Renaming_and_Combining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18C_xaoGd3dhET2NZdAayWxDW6M0GKK-_
"""

import pandas as pd
pd.set_option('display.max_rows', 5)
reviews = pd.read_csv("/content/winemag-data-130k-v2.csv", index_col=0)

"""**Renaming**"""

reviews.rename(columns={'points': 'score'})

reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'})

reviews.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')

"""**Combining**"""

canadian_youtube = pd.read_csv("/content/CAvideos.csv")
british_youtube = pd.read_csv("/content/GBvideos.csv")

pd.concat([canadian_youtube, british_youtube])

